import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { db } from '../firebase/config';
import { collection, onSnapshot, query, orderBy, doc, updateDoc, deleteDoc, writeBatch } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';

export default function ShoppingList() {
  const { currentUser } = useAuth();
  const navigate = useNavigate();
  const [listItems, setListItems] = useState([]);
  const [loading, setLoading] = useState(true);

  // Totals
  const totalEstimated = listItems.reduce((sum, item) => sum + (item.estimatedPrice * item.qty), 0);

  useEffect(() => {
    if (!currentUser) {
      navigate('/login');
      return;
    }

    const q = query(collection(db, 'users', currentUser.uid, 'shoppingList'), orderBy('addedAt', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setListItems(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      setLoading(false);
    });

    return () => unsubscribe();
  }, [currentUser, navigate]);

  // Handle Updates
  const updateItem = async (id, field, value) => {
    await updateDoc(doc(db, 'users', currentUser.uid, 'shoppingList', id), { [field]: value });
  };

  const removeItem = async (id) => {
    if (window.confirm("Remove this item?")) {
      await deleteDoc(doc(db, 'users', currentUser.uid, 'shoppingList', id));
    }
  };

  const handleClearList = async () => {
    if (!window.confirm("⚠️ Are you sure you want to delete ALL items from your shopping list?")) return;
    
    try {
      const batch = writeBatch(db);
      listItems.forEach((item) => {
        const itemRef = doc(db, 'users', currentUser.uid, 'shoppingList', item.id);
        batch.delete(itemRef);
      });
      await batch.commit();
    } catch (error) {
      console.error("Error clearing list:", error);
      alert("Failed to clear list.");
    }
  };

  // 1. PDF GENERATOR WITH DYNAMIC NAMING
  const handleSaveAsPDF = () => {
    // Get today's date formatted as DD-MM-YYYY
    const today = new Date().toLocaleDateString('en-GB').replace(/\//g, '-');
    const dynamicName = `KeralaVipani_Shopping_List_${today}`;
    
    // Temporarily change the document title so the browser names the PDF correctly
    const originalTitle = document.title;
    document.title = dynamicName;
    
    // Open Print Dialog
    window.print();
    
    // Change the title back immediately after
    document.title = originalTitle;
  };

  // 2. DIRECT WHATSAPP TEXT SHARING
  const handleWhatsAppShare = () => {
    const today = new Date().toLocaleDateString('en-GB');
    let message = `🛒 *KeralaVipani Shopping List* (${today})\n\n`;

    // Loop through list items and format them
    listItems.forEach(item => {
      // Don't include items they already checked off/bought
      if (!item.isBought) {
        message += `• ${item.name}`;
        if (item.qty > 1) message += ` (x${item.qty})`;
        message += ` - ₹${item.estimatedPrice * item.qty}\n`;
      }
    });

    message += `\n*Total Estimated:* ₹${totalEstimated}\n\n`;
message += `View live rates on: https://keralavipani.abidts.work`;

    // Encode the message and open WhatsApp URL Scheme
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  if (loading) return <div className="text-center py-20 text-gray-500 font-bold">Loading your list...</div>;

  return (
    <div className="max-w-3xl mx-auto mt-4 md:mt-8 pb-32 print:pb-0 print:mt-0">
      
      {/* HEADER WITH BUTTONS */}
      <div className="mb-8 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h2 className="text-3xl font-extrabold text-gray-900 flex items-center gap-3">
            🛒 Smart Shopping List
          </h2>
          <p className="text-gray-500 mt-2 print:hidden">
            ⚠️ Estimated prices are based on the <span className="font-bold text-gray-700">Kerala State Average</span>.
          </p>
          {/* Print-only subtitle */}
          <p className="hidden print:block text-gray-500 mt-1">Generated by KeralaVipani</p>
        </div>
        
        {/* ACTION BUTTONS (Hidden when printing PDF) */}
        {listItems.length > 0 && (
          <div className="flex flex-wrap items-center gap-2 print:hidden">
            
            {/* DIRECT WHATSAPP BUTTON */}
            <button 
              onClick={handleWhatsAppShare}
              className="px-4 py-2 bg-green-50 hover:bg-green-100 text-green-700 font-bold rounded-xl text-sm transition-colors flex items-center justify-center gap-2 shrink-0 border border-green-200"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
              WhatsApp
            </button>

            {/* SAVE AS PDF BUTTON */}
            <button 
              onClick={handleSaveAsPDF}
              className="px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-600 font-bold rounded-xl text-sm transition-colors flex items-center justify-center gap-2 shrink-0 border border-blue-100"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
              PDF
            </button>

            {/* CLEAR LIST BUTTON */}
            <button 
              onClick={handleClearList}
              className="px-4 py-2 bg-red-50 hover:bg-red-100 text-red-600 font-bold rounded-xl text-sm transition-colors flex items-center justify-center gap-2 shrink-0 border border-red-100"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
              Clear
            </button>
          </div>
        )}
      </div>

      {listItems.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-3xl border border-gray-100 print:hidden">
          <p className="text-lg text-gray-500 font-bold">Your list is empty.</p>
          <button onClick={() => navigate('/')} className="mt-4 px-6 py-2 bg-primary text-white font-bold rounded-xl">Go Add Items</button>
        </div>
      ) : (
        <div className="space-y-4 print:space-y-0">
          {listItems.map((item) => (
            <div key={item.id} className={`bg-white p-4 md:p-5 rounded-2xl border ${item.isBought ? 'border-emerald-200 bg-emerald-50/30' : 'border-gray-200'} shadow-sm transition-all flex flex-col md:flex-row gap-4 items-start md:items-center justify-between print:border-b print:border-x-0 print:border-t-0 print:rounded-none print:shadow-none print:p-2 print:bg-white`}>
              
              {/* Checkbox & Details */}
              <div className="flex items-start gap-4 flex-1 w-full">
                <input 
                  type="checkbox" 
                  checked={item.isBought}
                  onChange={(e) => updateItem(item.id, 'isBought', e.target.checked)}
                  className="w-6 h-6 mt-1 rounded border-gray-300 text-primary focus:ring-primary cursor-pointer print:mt-0 print:w-4 print:h-4"
                />
                <div className={item.isBought ? 'opacity-60 print:opacity-100' : ''}>
                  <h3 className={`text-lg font-bold text-gray-900 ${item.isBought ? 'line-through decoration-2 print:no-underline' : ''}`}>{item.name}</h3>
                  <p className="text-xs text-gray-500 font-medium">State Avg: ₹{item.estimatedPrice} / {item.unit} {item.qty > 1 && <span className="text-gray-800 font-bold ml-1">(Qty: {item.qty})</span>}</p>
                </div>
              </div>

              {/* Controls (Hidden in PDF to keep it clean) */}
              <div className="flex flex-wrap items-center justify-end gap-4 w-full md:w-auto print:hidden">
                {!item.isBought && (
                  <div className="flex items-center bg-gray-100 rounded-lg p-1">
                    <button onClick={() => updateItem(item.id, 'qty', Math.max(1, item.qty - 1))} className="w-8 h-8 flex items-center justify-center font-bold text-gray-600 hover:bg-white rounded-md">-</button>
                    <span className="w-8 text-center text-sm font-bold">{item.qty}</span>
                    <button onClick={() => updateItem(item.id, 'qty', item.qty + 1)} className="w-8 h-8 flex items-center justify-center font-bold text-gray-600 hover:bg-white rounded-md">+</button>
                  </div>
                )}

                <div className="w-24 text-right">
                  <p className="text-xs text-gray-400 font-bold">Est. Total</p>
                  <p className="text-lg font-black text-gray-900">₹{item.estimatedPrice * item.qty}</p>
                </div>

                <button onClick={() => removeItem(item.id)} className="p-2 text-gray-400 hover:text-red-500 bg-gray-50 hover:bg-red-50 rounded-lg transition-colors">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                </button>
              </div>

              {/* PDF Only: Clean Price Display */}
              <div className="hidden print:block text-right">
                <p className="font-black text-gray-900 text-lg">₹{item.estimatedPrice * item.qty}</p>
              </div>

            </div>
          ))}
        </div>
      )}

      {/* PDF ONLY: Footer Total */}
      {listItems.length > 0 && (
        <div className="hidden print:flex justify-between items-center mt-6 pt-4 border-t-2 border-gray-900">
          <h3 className="text-xl font-bold text-gray-900">Total Estimated Budget:</h3>
          <h3 className="text-2xl font-black text-gray-900">₹{totalEstimated}</h3>
        </div>
      )}

      {/* STICKY WEB FOOTER (Hidden in PDF) */}
      {listItems.length > 0 && (
        <div className="fixed bottom-0 left-0 w-full bg-white border-t border-gray-200 shadow-[0_-10px_40px_rgba(0,0,0,0.05)] z-40 px-4 py-4 md:px-8 print:hidden">
          <div className="max-w-3xl mx-auto flex justify-between items-center">
            <div>
              <p className="text-xs md:text-sm font-bold text-gray-500 uppercase tracking-wider">Total Estimated</p>
            </div>
            <div className="text-right">
              <p className="text-xl md:text-3xl font-black text-gray-900">₹{totalEstimated}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}